import type { CommandSummary } from "@opencode-remote/shared"

export const BUILTIN_COMMANDS: CommandSummary[] = [
  {
    name: "sessions",
    description: "Browse or resume previous sessions.",
    source: "built-in",
    hints: [],
    aliases: ["resume", "continue"],
  },
  {
    name: "workspaces",
    description: "Browse available workspaces.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "new",
    description: "Start a new session in the current workspace.",
    source: "built-in",
    hints: [],
    aliases: ["clear"],
  },
  {
    name: "models",
    description: "Open model selection.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "agents",
    description: "Switch the active agent.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "mcps",
    description: "Show connected MCP servers.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "connect",
    description: "Connect supported tools or providers.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "status",
    description: "Refresh the current session status.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "themes",
    description: "Change the interface theme.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "help",
    description: "Show help for slash commands and shortcuts.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "exit",
    description: "Exit the current flow.",
    source: "built-in",
    hints: [],
    aliases: ["quit", "q"],
  },
  {
    name: "editor",
    description: "Open the editor for composing input.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "skills",
    description: "Browse available skill commands.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "share",
    description: "Share the current session.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "rename",
    description: "Rename the current session.",
    source: "built-in",
    hints: ["Type a new title after the command."],
    aliases: [],
  },
  {
    name: "timeline",
    description: "Inspect the session timeline.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "fork",
    description: "Fork the current session.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "compact",
    description: "Compress the conversation into a shorter summary.",
    source: "built-in",
    hints: [],
    aliases: ["summarize"],
  },
  {
    name: "unshare",
    description: "Stop sharing the current session.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "undo",
    description: "Undo the last user turn.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "redo",
    description: "Redo the last reverted turn.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "timestamps",
    description: "Toggle message timestamps.",
    source: "built-in",
    hints: [],
    aliases: ["toggle-timestamps"],
  },
  {
    name: "thinking",
    description: "Toggle reasoning visibility.",
    source: "built-in",
    hints: [],
    aliases: ["toggle-thinking"],
  },
  {
    name: "copy",
    description: "Copy the session transcript.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
  {
    name: "export",
    description: "Export the current session transcript.",
    source: "built-in",
    hints: [],
    aliases: [],
  },
]
